# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crpn8plco6v97rbq4jtc/dds_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2026-10-06-r1"

containerPort: 5000

config:
  KAFKA_HOST: "rc1a-02p8am8as40u1qrb.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "xs9rNfQwnKUbUk8"
  KAFKA_CONSUMER_GROUP: "main-consumer-group"
  KAFKA_SOURCE_TOPIC: "dds-service"
  KAFKA_DESTINATION_TOPIC: "cdm-service"

  PG_WAREHOUSE_HOST: "rc1a-t86pisc5g6mdlg6r.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "user1"
  PG_WAREHOUSE_PASSWORD: "xs9rNfQwnKUbUk8"
  NAMESPACE_UUID: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
